Fix - post/private: Password protected button is not aligned (ED-2533)
elementor/hello-theme pull request #153
Opened 2021-04-06 13:20 UTC by nisan250

Now when the form for entering private post/page is showing the button aligned correctly with the text input for password.

2021-04-20 11:15 UTC, StyleShit commented on style.css
> +	Requires PHP: 5.6
@matipojo do we need that here? @nisan250 says it was automatically generated

2021-06-01 18:11 UTC, matipojo requested changes
Fix conflicts

2021-06-01 18:11 UTC, matipojo commented on assets/scss/theme/_general.scss
> +}
Add an empty line

2021-06-23 18:26 UTC, matipojo approved these changes

2021-06-23 18:27 UTC, matipojo requested changes
Please pull from develop

2021-07-07 18:36 UTC, matipojo requested changes
Please fix conflicts

2021-07-08 13:45 UTC, nisan250 commented
The issue have already fixed.

2021-07-08 13:45 UTC, closed without merging